//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a>
// Any modifications to this file will be lost upon recompilation of the source schema.
// Generated on: 2014.06.27 at 05:21:07 PM CEST
//
package model

import javax.xml.bind.annotation._
import collection.mutable

class ImmutableContext {

  var aggregatedProfiles = new mutable.HashSet[String]()
  var referencedContexts = new mutable.HashSet[String]()
  var referencedByContexts = new mutable.HashSet[String]()
  var data = new mutable.HashMap[String, String]()

  def setDataItem(name: String, value: String) {
    data.put(name, value)
  }

  def getDataItem(name: String): String = {
    if (!data.contains(name)) {
      throw new Exception("Context data does not contain key " + name)
    }

    data(name)
  }

  def getAggregatedProfiles = aggregatedProfiles

  def getReferencedContexts = referencedContexts

  def getReferencedByContexts = referencedByContexts

}